s/this\./this->/g

#
# Add the @header{} section after the options {} section.
#
/options {/ {
  h
}

/}/ {
  p
  H
  g
  /options {.*}/ {
    a 
    a // Auto generated by 'pitch.sed' script
    a @header {
    a #include "JavaScriptLexerBase.h"
    a #include "JavaScriptParserBase.h"
    # !compatibility: 'r' Commands As a GNU extension
    r Cpp/custom.h
    a
    a }
  }
}

/}/ {
  z
  h
  d
}

/.*/ {
  H
}
